name: 同时更新DNS和KV的IP
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *' # 每4小时运行一次
  # workflow_dispatch: # 手动触发

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the yx_ips script
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_DOMAIN_NAME: ${{ secrets.CF_DOMAIN_NAME }}
        CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      run: python yx_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add yx_ips.txt
        git commit -m "Update yx_ips.txt" || echo "No changes to commit"
        git push origin main

    - name: Set up environment for cfkv_ips.sh
      run: |
        echo "CF_DOMAIN=${{ secrets.CF_DOMAIN }}" >> $GITHUB_ENV
        echo "CF_TOKEN=${{ secrets.CF_TOKEN }}" >> $GITHUB_ENV
        echo "FILENAME=yx_ips.txt" >> $GITHUB_ENV

    - name: Make cfkv_ips.sh executable
      run: chmod +x ./cfkv_ips.sh

    - name: Run cfkv_ips.sh
      run: ./cfkv_ips.sh "${{ env.FILENAME }}"

